export const PRODUCT_SECTIONS = {
  ja: {
    enmaLabel: "Enma",
    enmaTitle: "閻魔",
    woodboxLabel: "Mokkan",
    woodboxTitle: "木函",
    orioriLabel: "Oriori",
    orioriTitle: "折々",
    orioriIntro: "折々の時間に寄り添う、三つの静かなサービス",
    buyButton: "購入する",
    specLabels: {
      origin: "生産地",
      producer: "生産者",
      process: "プロセス",
      variety: "品種",
      altitude: "標高",
      weight: "内容量",
      price: "価格",
      flavor: "フレーバーノート",
    },
  },

  en: {
    enmaLabel: "Enma",
    enmaTitle: "閻魔",
    woodboxLabel: "Mokkan",
    woodboxTitle: "木函",
    orioriLabel: "Oriori",
    orioriTitle: "折々",
    orioriIntro: "Three quiet services shaped for changing seasons",
    buyButton: "Buy",
    specLabels: {
      origin: "Origin",
      producer: "Producer",
      process: "Process",
      variety: "Variety",
      altitude: "Altitude",
      weight: "Weight",
      price: "Price",
      flavor: "Flavor Notes",
    },
  },

  es: {
    enmaLabel: "Enma",
    enmaTitle: "閻魔",
    woodboxLabel: "Mokkan",
    woodboxTitle: "木函",
    orioriLabel: "Oriori",
    orioriTitle: "折々",
    orioriIntro: "Tres servicios silenciosos para distintos momentos",
    buyButton: "Comprar",
    specLabels: {
      origin: "Origen",
      producer: "Productor",
      process: "Proceso",
      variety: "Variedad",
      altitude: "Altitud",
      weight: "Peso",
      price: "Precio",
      flavor: "Notas de sabor",
    },
  },
};

export const PRODUCT_DATA = {
  enma: [
    {
      id: "enma-ethiopia-dark",
      image: "/images/enma-1.jpg",
      category: "beans",
      size: "100g",
      title: {
        ja: "閻魔　深煎りの禅",
        en: "King ENMA Dark Roast",
        es: "King ENMA Dark Roast",
      },
      summary: {
        ja: "静かに残る苦味と余韻",
        en: "Deep bitterness with a quiet finish",
        es: "Deep bitterness with a quiet finish",
      },
      origin: "Sidama, Ethiopia",
      producer: "Nigusse Gemeda",
      process: "Washed",
      variety: "74112, Ethiopian Heirloom",
      altitude: "1,860–1,990m",
      weight: "100g",
      price: "¥1,780",
      priceNumber: 1780,
      flavor: "Tangerine, Bergamot, Darjeeling, Floral, Soft, Round, Sweet",
      link: "https://square.link/u/xxxxx",
      isSoldOut: false,
    },
    {
      id: "enma-ethiopia-light",
      image: "/images/enma-2.jpg",
      category: "beans",
      size: "100g",
      title: {
        ja: "閻魔　エチオピア　浅煎り",
        en: "ENMA Ethiopia Light Roast",
        es: "ENMA Ethiopia Light Roast",
      },
      summary: {
        ja: "明るさと輪郭のある浅煎り",
        en: "A light roast with brightness and contour",
        es: "A light roast with brightness and contour",
      },
      origin: "Sidama, Ethiopia",
      producer: "Karamo / Nigusse Gemeda",
      process: "Natural",
      variety: "74158, Ethiopian Heirloom",
      altitude: "2,320–2,400m",
      weight: "100g",
      price: "¥2,100",
      priceNumber: 2100,
      flavor: "Blackberry, Strawberry, Full Body",
      link: "https://square.link/u/xxxxx",
      isSoldOut: false,
    },
    {
      id: "enma-burundi-light",
      image: "/images/enma-3.jpg",
      category: "beans",
      size: "100g",
      title: {
        ja: "閻魔　ブルンジ　浅煎り",
        en: "ENMA Burundi Light Roast",
        es: "ENMA Burundi Light Roast",
      },
      summary: {
        ja: "明るさと透明感、やわらかな甘さ",
        en: "Brightness and clarity with a gentle sweetness",
        es: "Brightness and clarity with a gentle sweetness",
      },
      origin: "Muyinga, Burundi",
      producer: "Karambo Washing Station",
      process: "Washed",
      variety: "Bourbon",
      altitude: "1500–1700m",
      weight: "100g",
      price: "¥1,980",
      priceNumber: 1980,
      flavor: "Orange, Plum, Apricot, Floral, Black Tea",
      link: "https://square.link/u/xxxxx",
      isSoldOut: false,
    },
  ],

  woodbox: [
    {
      id: "woodbox-ethiopia",
      image: "/images/woodbox-1.jpg",
      category: "woodbox",
      size: "100g",
      title: {
        ja: "木函　コロンビア　ゲイシャ",
        en: "WOOD BOX Colombia Geisha",
        es: "WOOD BOX Colombia Geisha",
      },
      modalTitle: {
        ja: "木函　コロンビア\nゲイシャ",
        en: "WOOD BOX Colombia\nGeisha",
        es: "WOOD BOX Colombia\nGeisha",
      },
      summary: {
        ja: "華やかさと丸みを備えた特別な一本",
        en: "A special release with floral clarity and round sweetness",
        es: "A special release with floral clarity and round sweetness",
      },
      origin: "Herrera, Tolima, Colombia",
      producer: "Newerley Gutierrez",
      process: "Anaerobic Honey",
      variety: "Geisha",
      altitude: "1,800–2,100m",
      weight: "100g",
      price: "¥3,200",
      priceNumber: 3200,
      flavor: "Orange, Apricot, Walnut, Honey, Bergamot, Smooth, Round",
      link: "https://square.link/u/xxxxx",
      isSoldOut: true,
    },
    {
      id: "woodbox-geisha",
      image: "/images/woodbox-2.jpg",
      category: "woodbox",
      size: "100g",
      title: {
        ja: "木函　ホンジュラス　ゲイシャ",
        en: "WOOD BOX Honduras Geisha",
        es: "WOOD BOX Honduras Geisha",
      },
      modalTitle: {
        ja: "木函　ホンジュラス\nゲイシャ",
        en: "WOOD BOX Honduras\nGeisha",
        es: "WOOD BOX Honduras\nGeisha",
      },
      summary: {
        ja: "木箱で届く贈り物のような静かなプレミアム",
        en: "A quiet premium format, like a gift",
        es: "A quiet premium format, like a gift",
      },
      origin: "La Paz, Honduras",
      producer: "Otilio Hernandez",
      process: "Washed",
      variety: "Geisha",
      altitude: "1750–1800m",
      weight: "100g",
      price: "¥2,600",
      priceNumber: 2600,
      flavor:
        "Floral, Earl Grey, Stone Fruit, Pear, Honey, Bright Acidity, Round Mouthfeel, Elegant",
      link: "https://square.link/u/xxxxx",
      isSoldOut: false,
    },
  ],

  oriori: [
    {
      id: "oriori-subscription",
      category: "subscription",
      size: "100g",
      image: "/images/oriori-1.jpg",
      title: {
        ja: "サブスクリプション",
        en: "Subscription",
        es: "Subscription",
      },
      summary: {
        ja: "季節に寄り添う定期便",
        en: "A recurring delivery shaped by the season",
        es: "A recurring delivery shaped by the season",
      },

      plans: {
        ja: [
          {
            id: "light",
            name: "Light",
            badge: null,
            lead: "まずは体験",
            price: "¥2,200",
            priceNumber: 2200,
            frequency: "月1回",
            shipping: "送料無料",
            items: ["閻魔 100g ×1", "珈琲バッグ ×2"],
            note: "閻魔100gを1つと珈琲バッグ2個を合わせた、静かに始めるための最初の定期便。",
            button: "Lightを選ぶ",
          },
          {
            id: "basic",
            name: "Basic",
            badge: "一番人気",
            lead: "日常に馴染む",
            price: "¥3,600",
            priceNumber: 3600,
            frequency: "月1回",
            shipping: "送料無料",
            items: ["閻魔 100g ×2", "珈琲バッグ ×4"],
            note: "閻魔100gを2つと珈琲バッグ4個を組み合わせた、日常に最も馴染む主力プラン。",
            button: "Basicを選ぶ",
          },
          {
            id: "premium",
            name: "Premium",
            badge: null,
            lead: "静かな特別便",
            price: "¥4,600",
            priceNumber: 4600,
            frequency: "月1回",
            shipping: "送料無料",
            items: ["閻魔 100g ×2", "珈琲バッグ ×3", "お茶バッグ ×3"],
            note: "閻魔100gを2つ、珈琲バッグ3個に加え、お茶バッグ3個を収めた特別な構成。鎌倉の寺の空気感をそのままご自宅で味わっていただくために、お茶を含めています。珈琲とお茶、どちらにも通底する“禅の余白”を静かに楽しむためのプレミアムな定期便。",
            button: "Premiumを選ぶ",
          },
        ],

        en: [
          {
            id: "light",
            name: "Light",
            badge: null,
            lead: "A quiet first step",
            price: "¥2,200",
            priceNumber: 2200,
            frequency: "Monthly",
            shipping: "Free Shipping",
            items: ["ENMA 100g ×1", "Coffee Bag ×2"],
            note: "A simple first subscription with one 100g ENMA and two Coffee Bags.",
            button: "Choose Light",
          },
          {
            id: "basic",
            name: "Basic",
            badge: "Most Selected",
            lead: "For everyday rhythm",
            price: "¥3,600",
            priceNumber: 3600,
            frequency: "Monthly",
            shipping: "Free Shipping",
            items: ["ENMA 100g ×2", "Coffee Bag ×4"],
            note: "Our core everyday plan with two 100g ENMA bags and four Coffee Bags.",
            button: "Choose Basic",
          },
          {
            id: "premium",
            name: "Premium",
            badge: null,
            lead: "A quieter special delivery",
            price: "¥4,600",
            priceNumber: 4600,
            frequency: "Monthly",
            shipping: "Free Shipping",
            items: ["ENMA 100g ×2", "Coffee Bag ×3", "Tea Bag ×3"],
            note: "A premium composition including two 100g ENMA, three Coffee Bags, and three Tea Bags. The addition of tea is intended to bring the atmosphere of a Kamakura temple into your home. A quiet subscription designed to experience the shared stillness between coffee and tea.",
            button: "Choose Premium",
          },
        ],

        es: [
          {
            id: "light",
            name: "Light",
            badge: null,
            lead: "Una primera experiencia",
            price: "¥2,200",
            priceNumber: 2200,
            frequency: "Mensual",
            shipping: "Envío gratis",
            items: ["ENMA 100g ×1", "Coffee Bag ×2"],
            note: "Una composición premium con dos ENMA de 100g, tres Coffee Bags y tres Tea Bags. La inclusión del té permite recrear en casa la atmósfera de un templo en Kamakura. Una suscripción pensada para disfrutar de la calma compartida entre café y té.",
            button: "Elegir Light",
          },
          {
            id: "basic",
            name: "Basic",
            badge: "Más elegido",
            lead: "Para la vida diaria",
            price: "¥3,600",
            priceNumber: 3600,
            frequency: "Mensual",
            shipping: "Envío gratis",
            items: ["ENMA 100g ×2", "Coffee Bag ×4"],
            note: "Nuestro plan principal para el día a día con dos bolsas de ENMA de 100g y cuatro Coffee Bags.",
            button: "Elegir Basic",
          },
          {
            id: "premium",
            name: "Premium",
            badge: null,
            lead: "Una entrega más especial",
            price: "¥4,600",
            priceNumber: 4600,
            frequency: "Mensual",
            shipping: "Envío gratis",
            items: ["ENMA 100g ×2", "Coffee Bag ×3", "Tea Bag ×3"],
            note:
              "Un plan más especial con dos bolsas de ENMA de 100g, tres Coffee Bags y tres Tea Bags.",
            button: "Elegir Premium",
          },
        ],
      },

      link: "https://square.link/u/xxxxx",
    },
    {
      id: "oriori-bag",
      image: "/images/coffee-bag.jpg",
      title: {
        ja: "バッグシリーズ",
        en: "Bag Series",
        es: "Bag Series",
      },
      modalTitle: {
        ja: "バッグシリーズ",
        en: "Bag Series",
        es: "Bag Series",
      },
      summary: {
        ja: "日々の合間に寄り添う、静かな一杯",
        en: "A quiet cup for everyday moments",
        es: "Una taza tranquila para el día a día",
      },

     variants: [
  {
    id: "coffee-bag",
    tabLabel: {
      ja: "閻魔",
      en: "ENMA",
      es: "ENMA",
    },
    name: {
      ja: "珈琲バッグ　閻魔　深煎りの禅",
      en: "Coffee Bag – ENMA / Deep Roasted Zen",
      es: "Bolsa de café – ENMA / Zen de tueste profundo",
    },
    note: {
      ja: "静かに残る苦味と余韻",
      en: "Deep bitterness with a quiet finish",
      es: "Amargor profundo con final suave",
    },
    brew: {
      ja: [
        "マグカップに入れ、160ccのお湯を注ぎ、2分ほど待ってお召し上がりください。",
      ],
      en: [
        "Place the bag in a mug, pour 160ml of hot water, and wait about 2 minutes.",
      ],
      es: [
        "Coloque la bolsa en una taza, vierta 160ml de agua caliente y espere unos 2 minutos.",
      ],
    },
    quantities: [
      { id: "1", label: "1個" },
      { id: "3", label: "3個" },
      { id: "5", label: "5個" },
    ],
    button: {
      ja: "購入する",
      en: "Buy",
      es: "Comprar",
    },
    link: "https://square.link/u/xxxxx",
  },
  {
    id: "tea-bag",
    tabLabel: {
      ja: "地蔵",
      en: "JIZO",
      es: "JIZO",
    },
    name: {
      ja: "お茶バッグ　地蔵　静寂の余韻",
      en: "Tea Bag – JIZO / Quiet Aftertaste",
      es: "Bolsa de té – JIZO / Eco tranquilo",
    },
    note: {
      ja: "寺の時間に寄り添う、やわらかな一杯",
      en: "A softer, quieter cup",
      es: "Una taza suave y tranquila",
    },
    teaTypes: {
      ja: ["煎茶"],
      en: ["Sencha"],
      es: ["Sencha"],
    },
    brew: {
      ja: [
        "一煎目：200ccで1分",
        "二煎目：200ccで10秒",
        "三煎目：200ccで10秒",
      ],
      en: [
        "1st infusion: 200ml for 1 minute",
        "2nd infusion: 200ml for 10 seconds",
        "3rd infusion: 200ml for 10 seconds",
      ],
      es: [
        "Primera infusión: 200ml durante 1 minuto",
        "Segunda infusión: 200ml durante 10 segundos",
        "Tercera infusión: 200ml durante 10 segundos",
      ],
    },
    quantities: [
      { id: "1", label: "1個" },
      { id: "3", label: "3個" },
      { id: "5", label: "5個" },
    ],
    button: {
      ja: "購入する",
      en: "Buy",
      es: "Comprar",
    },
    link: "https://square.link/u/xxxxx",
  },
],

      isSoldOut: false,
    },
    {
      id: "oriori-wheel",
      image: "/images/oriori.wheel.jpg",
      title: {
        ja: "フレーバーホイール",
        en: "Flavor Wheel",
        es: "Flavor Wheel",
      },
      modalTitle: {
        ja: "フレーバーホイール",
        en: "Flavor Wheel",
        es: "Flavor Wheel",
      },
      summary: {
        ja: "味わいを記録し、言葉にするためのサイト",
        en: "A site for recording and describing flavor",
        es: "Un sitio para registrar y expresar sabores",
      },
      description: {
        ja: "選んだフレーバーを記録し、コメントとともに保存できるテイスティング用サイトです。",
        en: "A tasting site where you can record selected flavors and save them with notes.",
        es: "Un sitio de cata donde puedes registrar los sabores seleccionados y guardarlos con notas.",
      },
      buttonLabel: {
        ja: "サイトを見る",
        en: "Open Site",
        es: "Ver sitio",
      },
      link: "https://flavorcoffeewheel.com"
    },
  ],
};