export const PRODUCT_SECTIONS = {
  ja: {
    enmaLabel: "Enma",
    enmaTitle: "閻魔",
    woodboxLabel: "Mokkan",
    woodboxTitle: "木函",
    orioriLabel: "Oriori",
    orioriTitle: "折々",
    orioriIntro: "折々の時間に寄り添う、三つの静かなサービス",
    buyButton: "購入する",
    specLabels: {
      origin: "生産地",
      producer: "生産者",
      process: "プロセス",
      variety: "品種",
      altitude: "標高",
      weight: "内容量",
      price: "価格",
      flavor: "フレーバーノート",
    },
  },

  en: {
    enmaLabel: "Enma",
    enmaTitle: "閻魔",
    woodboxLabel: "Mokkan",
    woodboxTitle: "木函",
    orioriLabel: "Oriori",
    orioriTitle: "折々",
    orioriIntro: "Three quiet services shaped for changing seasons",
    buyButton: "Buy",
    specLabels: {
      origin: "Origin",
      producer: "Producer",
      process: "Process",
      variety: "Variety",
      altitude: "Altitude",
      weight: "Weight",
      price: "Price",
      flavor: "Flavor Notes",
    },
  },

  es: {
    enmaLabel: "Enma",
    enmaTitle: "閻魔",
    woodboxLabel: "Mokkan",
    woodboxTitle: "木函",
    orioriLabel: "Oriori",
    orioriTitle: "折々",
    orioriIntro: "Tres servicios silenciosos para distintos momentos",
    buyButton: "Comprar",
    specLabels: {
      origin: "Origen",
      producer: "Productor",
      process: "Proceso",
      variety: "Variedad",
      altitude: "Altitud",
      weight: "Peso",
      price: "Precio",
      flavor: "Notas de sabor",
    },
  },
};

export const PRODUCT_DATA = {
  enma: [
    {
      id: "enma-ethiopia-dark",
      image: "/images/enma-1.jpg",
      title: {
        ja: "閻魔　深煎りの禅",
        en: "King ENMA Dark Roast",
        es: "King ENMA Dark Roast",
      },
      summary: {
        ja: "静かに残る苦味と余韻",
        en: "Deep bitterness with a quiet finish",
        es: "Deep bitterness with a quiet finish",
      },
      origin: "Sidama, Ethiopia",
      producer: "Nigusse Gemeda",
      process: "Washed",
      variety: "74112, Ethiopian Heirloom",
      altitude: "1,860–1,990m",
      weight: "180g",
      price: "¥1,780",
      flavor: "Tangerine, Bergamot, Darjeeling, Floral, Soft, Round, Sweet",
      link: "https://square.link/u/xxxxx",
      isSoldOut: false,
    },
    {
      id: "enma-ethiopia-light",
      image: "/images/enma-2.jpg",
      title: {
        ja: "閻魔　エチオピア　浅煎り",
        en: "ENMA Ethiopia Light Roast",
        es: "ENMA Ethiopia Light Roast",
      },
      summary: {
        ja: "明るさと輪郭のある浅煎り",
        en: "A light roast with brightness and contour",
        es: "A light roast with brightness and contour",
      },
      origin: "Sidama, Ethiopia",
      producer: "Karamo / Nigusse Gemeda",
      process: "Natural",
      variety: "74158, Ethiopian Heirloom",
      altitude: "2,320–2,400m",
      weight: "180g",
      price: "¥2,100",
      flavor: "Blackberry, Strawberry, Full Body",
      link: "https://square.link/u/xxxxx",
      isSoldOut: false,
    },
    {
      id: "enma-burundi-light",
      image: "/images/enma-3.jpg",
      title: {
        ja: "閻魔　ブルンジ　浅煎り",
        en: "ENMA Burundi Light Roast",
        es: "ENMA Burundi Light Roast",
      },
      summary: {
        ja: "明るさと透明感、やわらかな甘さ",
        en: "Brightness and clarity with a gentle sweetness",
        es: "Brightness and clarity with a gentle sweetness",
      },
      origin: "Muyinga, Burundi",
      producer: "Karambo Washing Station",
      process: "Washed",
      variety: "Bourbon",
      altitude: "1500–1700m",
      weight: "180g",
      price: "¥1,980",
      flavor: "Orange, Plum, Apricot, Floral, Black Tea",
      link: "https://square.link/u/xxxxx",
      isSoldOut: false,
    },
  ],

  woodbox: [
    {
      id: "woodbox-ethiopia",
      image: "/images/woodbox-1.jpg",
      title: {
        ja: "木函　コロンビア　ゲイシャ",
        en: "WOOD BOX Colombia Geisha",
        es: "WOOD BOX Colombia Geisha",
      },
      modalTitle: {
        ja: "木函　コロンビア\nゲイシャ",
        en: "WOOD BOX Colombia\nGeisha",
        es: "WOOD BOX Colombia\nGeisha",
      },
      summary: {
        ja: "華やかさと丸みを備えた特別な一本",
        en: "A special release with floral clarity and round sweetness",
        es: "A special release with floral clarity and round sweetness",
      },
      origin: "Herrera, Tolima, Colombia",
      producer: "Newerley Gutierrez",
      process: "Anaerobic Honey",
      variety: "Geisha",
      altitude: "1,800–2,100m",
      weight: "100",
      price: "¥3,200",
      flavor: "Orange, Apricot, Walnut, Honey, Bergamot, Smooth, Round",
      link: "https://square.link/u/xxxxx",
      isSoldOut: true,
    },
    {
      id: "woodbox-geisha",
      image: "/images/woodbox-2.jpg",
      title: {
        ja: "木函　ホンジュラス　ゲイシャ",
        en: "WOOD BOX Honduras Geisha",
        es: "WOOD BOX Honduras Geisha",
      },
      modalTitle: {
        ja: "木函　ホンジュラス\nゲイシャ",
        en: "WOOD BOX Honduras\nGeisha",
        es: "WOOD BOX Honduras\nGeisha",
      },
      summary: {
        ja: "木箱で届く贈り物のような静かなプレミアム",
        en: "A quiet premium format, like a gift",
        es: "A quiet premium format, like a gift",
      },
      origin: "La Paz, Honduras",
      producer: "Otilio Hernandez",
      process: "Washed",
      variety: "Geisha",
      altitude: "1750–1800m",
      weight: "100g",
      price: "¥2,600",
      flavor:
        "Floral, Earl Grey, Stone Fruit, Pear, Honey, Bright Acidity, Round Mouthfeel, Elegant",
      link: "https://square.link/u/xxxxx",
      isSoldOut: false,
    },
  ],

  oriori: [
    {
      id: "oriori-subscription",
      image: "/images/oriori-1.jpg",
      title: {
        ja: "サブスクリプション",
        en: "Subscription",
        es: "Subscription",
      },
      summary: {
        ja: "季節に寄り添う定期便",
        en: "A recurring delivery shaped by the season",
        es: "A recurring delivery shaped by the season",
      },

      plans: {
        ja: [
          {
            id: "light",
            name: "Light",
            badge: null,
            lead: "まずは体験",
            price: "¥2,200",
            frequency: "月1回",
            shipping: "送料無料",
            items: ["閻魔 ×1", "珈琲バッグ ×3"],
            note: "静かに始めるための、最初の定期便。",
            button: "Lightを選ぶ",
          },
          {
            id: "basic",
            name: "Basic",
            badge: "一番人気",
            lead: "日常に馴染む",
            price: "¥3,500",
            frequency: "月1回",
            shipping: "送料無料",
            items: ["閻魔 ×2", "珈琲バッグ ×4"],
            note: "量と満足度のバランスが最も良い主力プラン。",
            button: "Basicを選ぶ",
          },
          {
            id: "premium",
            name: "Premium",
            badge: null,
            lead: "静かな特別便",
            price: "¥3,900",
            frequency: "月1回",
            shipping: "送料無料",
            items: ["木函 ×1", "閻魔 ×1", "珈琲バッグ ×2"],
            note: "特別感と日常の両方を含んだ、折々らしい定期便。",
            button: "Premiumを選ぶ",
          },
        ],

        en: [
          {
            id: "light",
            name: "Light",
            badge: null,
            lead: "A quiet first step",
            price: "¥2,200",
            frequency: "Monthly",
            shipping: "Shipping added at checkout*",
            items: ["ENMA ×1", "Coffee Bag ×3"],
            note:
              "A simple recurring delivery to begin with.\n*International shipping is added at checkout.",
            button: "Choose Light",
          },
          {
            id: "basic",
            name: "Basic",
            badge: "Most Selected",
            lead: "For everyday rhythm",
            price: "¥3,500",
            frequency: "Monthly",
            shipping: "Shipping added at checkout*",
            items: ["ENMA ×2", "Coffee Bag ×4"],
            note:
              "The most balanced plan for daily life. \n*International shipping is added at checkout.",
            button: "Choose Basic",
          },
          {
            id: "premium",
            name: "Premium",
            badge: null,
            lead: "A quieter special delivery",
            price: "¥3,900",
            frequency: "Monthly",
            shipping: "Shipping added at checkout*",
            items: ["WOOD BOX ×1", "ENMA ×1", "Coffee Bag ×2"],
            note:
              "A more composed plan with both premium and everyday cups. \n*International shipping is added at checkout.",
            button: "Choose Premium",
          },
        ],

        es: [
          {
            id: "light",
            name: "Light",
            badge: null,
            lead: "Una primera experiencia",
            price: "¥2,200",
            frequency: "Mensual",
            shipping: "Envío calculado al finalizar*",
            items: ["ENMA ×1", "Coffee Bag ×3"],
            note:
              "Una suscripción sencilla para empezar.\n*El envío internacional se calcula al finalizar la compra.",
            button: "Elegir Light",
          },
          {
            id: "basic",
            name: "Basic",
            badge: "Más elegido",
            lead: "Para la vida diaria",
            price: "¥3,500",
            frequency: "Mensual",
            shipping: "Envío calculado al finalizar*",
            items: ["ENMA ×2", "Coffee Bag ×4"],
            note:
              "El plan más equilibrado para el día a día. \n*El envío internacional se calcula al finalizar la compra.",
            button: "Elegir Basic",
          },
          {
            id: "premium",
            name: "Premium",
            badge: null,
            lead: "Una entrega más especial",
            price: "¥3,900",
            frequency: "Mensual",
            shipping: "Envío calculado al finalizar*",
            items: ["WOOD BOX ×1", "ENMA ×1", "Coffee Bag ×2"],
            note:
              "Una propuesta más especial entre lo cotidiano y lo excepcional. \n*El envío internacional se calcula al finalizar la compra.",
            button: "Elegir Premium",
          },
        ],
      },

      link: "https://square.link/u/xxxxx",
    },
{
  id: "oriori-bag",
  image: "/images/coffee-bag.jpg",
  title: {
    ja: "珈琲バッグ",
    en: "Coffee Bag",
    es: "Coffee Bag",
  },
  modalTitle: {
    ja: "珈琲バッグ",
    en: "Coffee Bag",
    es: "Coffee Bag",
  },
  summary: {
    ja: "日々の合間に寄り添う、静かな一杯",
    en: "A quiet cup for everyday moments",
    es: "Una taza tranquila para el día a día",
  },
  brew: {
    ja: [
      "バッグをマグカップに入れる",
      "お湯 160cc を注ぐ",
      "2分待つ",
      "軽く揺らして取り出す",
    ],
    en: [
      "Place the bag in a cup",
      "Pour 160ml of hot water",
      "Wait 2 minutes",
      "Gently move and remove",
    ],
    es: [
      "Colocar la bolsa en la taza",
      "Verter 160ml de agua caliente",
      "Esperar 2 minutos",
      "Mover suavemente y retirar",
    ],
  },
  variants: [
    {
      id: "enma-dark",
      name: {
        ja: "閻魔　深煎りの禅",
        en: "ENMA Dark Roast",
        es: "ENMA Dark Roast",
      },
      note: {
        ja: "静かに残る苦味と余韻",
        en: "Deep bitterness with a quiet finish",
        es: "Amargor profundo con final suave",
      },
    },
    {
      id: "tea",
      name: {
        ja: "お茶バッグ",
        en: "Tea Bag",
        es: "Tea Bag",
      },
      note: {
        ja: "寺の時間に寄り添う、やわらかな一杯",
        en: "A softer, quieter cup",
        es: "Una taza suave y tranquila",
      },
    },
  ],
  link: "https://square.link/u/xxxxx",
  isSoldOut: false,
},
    {
      id: "oriori-wheel",
      image: "/images/atmosphere-2.jpg",
      title: {
        ja: "フレーバーホイール",
        en: "Flavor Wheel",
        es: "Flavor Wheel",
      },
      summary: {
        ja: "味わいを記録し、言葉にするためのサイト",
        en: "A site for recording and describing flavor",
        es: "A site for recording and describing flavor",
      },
      origin: "—",
      producer: null,
      process: "—",
      variety: "—",
      altitude: "—",
      link: "https://square.link/u/xxxxx",
    },
  ],
  
};