export const PRODUCT_SECTIONS = {
  ja: {
    enmaLabel: "Enma",
    enmaTitle: "閻魔",
    woodboxLabel: "Wood Box",
    woodboxTitle: "木棺",
    orioriLabel: "ORIORI",
    orioriTitle: "折々",
    orioriIntro: "折々の時間に寄り添う、三つの静かなサービス",
    buyButton: "購入する",
    specLabels: {
      origin: "生産地",
      producer: "生産者",
      variety: "品種",
      process: "プロセス",
      altitude: "標高",
    },
  },

  en: {
    enmaLabel: "Enma",
    enmaTitle: "Enma",
    woodboxLabel: "Wood Box",
    woodboxTitle: "Wood Box",
    orioriLabel: "ORIORI",
    orioriTitle: "Oriori",
    orioriIntro: "Three quiet services shaped for changing seasons",
    buyButton: "Buy",
    specLabels: {
      origin: "Origin",
      producer: "Producer",
      variety: "Variety",
      process: "Process",
      altitude: "Altitude",
    },
  },

  es: {
    enmaLabel: "Enma",
    enmaTitle: "Enma",
    woodboxLabel: "Wood Box",
    woodboxTitle: "Caja de Madera",
    orioriLabel: "ORIORI",
    orioriTitle: "Oriori",
    orioriIntro: "Tres servicios silenciosos para distintos momentos",
    buyButton: "Comprar",
    specLabels: {
      origin: "Origen",
      producer: "Productor",
      variety: "Variedad",
      process: "Proceso",
      altitude: "Altitud",
    },
  },
};

export const PRODUCT_DATA = {
  ja: {
    enma: [
      {
        id: "enma-ethiopia-dark",
        image: "/images/enma-1.jpg",
        title: "エチオピア 深煎り",
        summary: "しっかりとした苦味と静かな余韻",
        origin: "エチオピア",
        producer: null,
        variety: "在来種",
        process: "ウォッシュド",
        altitude: "1,800–2,000m",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "enma-ethiopia-light",
        image: "/images/enma-2.jpg",
        title: "エチオピア 浅煎り",
        summary: "華やかさと輪郭が立つ浅煎り",
        origin: "エチオピア",
        producer: null,
        variety: "在来種",
        process: "ウォッシュド",
        altitude: "1,800–2,000m",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "enma-burundi-light",
        image: "/images/enma-3.jpg",
        title: "ブルンジ 浅煎り",
        summary: "明るさと透明感のある味わい",
        origin: "ブルンジ",
        producer: null,
        variety: "ブルボン",
        process: "ウォッシュド",
        altitude: "1,700–1,900m",
        link: "https://square.link/u/xxxxx",
      },
    ],

    woodbox: [
      {
        id: "woodbox-ethiopia",
        image: "/images/woodbox-1.jpg",
        title: "エチオピア 木棺",
        summary: "限られたロットを収めた特別仕様",
        origin: "エチオピア",
        producer: null,
        variety: "在来種",
        process: "ウォッシュド",
        altitude: "1,900–2,100m",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "woodbox-geisha",
        image: "/images/woodbox-2.jpg",
        title: "ゲイシャ 木棺",
        summary: "贈り物のように静かに届ける上位仕様",
        origin: "ホンジュラス",
        producer: null,
        variety: "ゲイシャ",
        process: "ウォッシュド",
        altitude: "1,500–1,700m",
        link: "https://square.link/u/xxxxx",
      },
    ],

    oriori: [
      {
        id: "oriori-subscription",
        image: "/images/oriori-1.jpg",
        title: "サブスクリプション",
        summary: "月ごとの移ろいを届ける定期便",
        origin: "時期により変更",
        producer: null,
        variety: "時期により変更",
        process: "時期により変更",
        altitude: "時期により変更",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "oriori-bag",
        image: "/images/oriori-2.jpg",
        title: "コーヒーバッグ",
        summary: "日々の合間に楽しむための一杯",
        origin: "時期により変更",
        producer: null,
        variety: "時期により変更",
        process: "時期により変更",
        altitude: "時期により変更",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "oriori-wheel",
        image: "/images/atmosphere-2.jpg",
        title: "フレーバーホイール",
        summary: "味わいを記録し言葉にするためのサイト",
        origin: "—",
        producer: null,
        variety: "—",
        process: "—",
        altitude: "—",
        link: "https://square.link/u/xxxxx",
      },
    ],
  },

  en: {
    enma: [
      {
        id: "enma-ethiopia-dark",
        image: "/images/enma-1.jpg",
        title: "Ethiopia Dark Roast",
        summary: "Deep bitterness with a quiet finish",
        origin: "Ethiopia",
        producer: null,
        variety: "Heirloom",
        process: "Washed",
        altitude: "1,800–2,000m",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "enma-ethiopia-light",
        image: "/images/enma-2.jpg",
        title: "Ethiopia Light Roast",
        summary: "A light roast with brightness and contour",
        origin: "Ethiopia",
        producer: null,
        variety: "Heirloom",
        process: "Washed",
        altitude: "1,800–2,000m",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "enma-burundi-light",
        image: "/images/enma-3.jpg",
        title: "Burundi Light Roast",
        summary: "Clean and bright in character",
        origin: "Burundi",
        producer: null,
        variety: "Bourbon",
        process: "Washed",
        altitude: "1,700–1,900m",
        link: "https://square.link/u/xxxxx",
      },
    ],

    woodbox: [
      {
        id: "woodbox-ethiopia",
        image: "/images/woodbox-1.jpg",
        title: "Ethiopia Wood Box",
        summary: "A special format for a limited lot",
        origin: "Ethiopia",
        producer: null,
        variety: "Heirloom",
        process: "Washed",
        altitude: "1,900–2,100m",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "woodbox-geisha",
        image: "/images/woodbox-2.jpg",
        title: "Geisha Wood Box",
        summary: "A quiet premium format, like a gift",
        origin: "Honduras",
        producer: null,
        variety: "Geisha",
        process: "Washed",
        altitude: "1,500–1,700m",
        link: "https://square.link/u/xxxxx",
      },
    ],

    oriori: [
      {
        id: "oriori-subscription",
        image: "/images/oriori-1.jpg",
        title: "Subscription",
        summary: "A recurring delivery shaped by the season",
        origin: "Changes by release",
        producer: null,
        variety: "Changes by release",
        process: "Changes by release",
        altitude: "Changes by release",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "oriori-bag",
        image: "/images/oriori-2.jpg",
        title: "Coffee Bag",
        summary: "A quiet cup for daily pauses",
        origin: "Changes by release",
        producer: null,
        variety: "Changes by release",
        process: "Changes by release",
        altitude: "Changes by release",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "oriori-wheel",
        image: "/images/atmosphere-2.jpg",
        title: "Flavor Wheel",
        summary: "A site for recording and describing flavor",
        origin: "—",
        producer: null,
        variety: "—",
        process: "—",
        altitude: "—",
        link: "https://square.link/u/xxxxx",
      },
    ],
  },

  es: {
    enma: [
      {
        id: "enma-ethiopia-dark",
        image: "/images/enma-1.jpg",
        title: "Etiopía Tueste Oscuro",
        summary: "Amargor profundo con un final silencioso",
        origin: "Etiopía",
        producer: null,
        variety: "Heirloom",
        process: "Lavado",
        altitude: "1,800–2,000m",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "enma-ethiopia-light",
        image: "/images/enma-2.jpg",
        title: "Etiopía Tueste Claro",
        summary: "Un tueste claro con brillo y contorno",
        origin: "Etiopía",
        producer: null,
        variety: "Heirloom",
        process: "Lavado",
        altitude: "1,800–2,000m",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "enma-burundi-light",
        image: "/images/enma-3.jpg",
        title: "Burundi Tueste Claro",
        summary: "Limpio y luminoso en carácter",
        origin: "Burundi",
        producer: null,
        variety: "Bourbon",
        process: "Lavado",
        altitude: "1,700–1,900m",
        link: "https://square.link/u/xxxxx",
      },
    ],

    woodbox: [
      {
        id: "woodbox-ethiopia",
        image: "/images/woodbox-1.jpg",
        title: "Caja de Madera Etiopía",
        summary: "Una edición especial para un lote limitado",
        origin: "Etiopía",
        producer: null,
        variety: "Heirloom",
        process: "Lavado",
        altitude: "1,900–2,100m",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "woodbox-geisha",
        image: "/images/woodbox-2.jpg",
        title: "Caja de Madera Geisha",
        summary: "Un formato premium, sereno como un regalo",
        origin: "Honduras",
        producer: null,
        variety: "Geisha",
        process: "Lavado",
        altitude: "1,500–1,700m",
        link: "https://square.link/u/xxxxx",
      },
    ],

    oriori: [
      {
        id: "oriori-subscription",
        image: "/images/oriori-1.jpg",
        title: "Suscripción",
        summary: "Una entrega periódica según la estación",
        origin: "Cambia según la edición",
        producer: null,
        variety: "Cambia según la edición",
        process: "Cambia según la edición",
        altitude: "Cambia según la edición",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "oriori-bag",
        image: "/images/oriori-2.jpg",
        title: "Coffee Bag",
        summary: "Una taza tranquila para las pausas diarias",
        origin: "Cambia según la edición",
        producer: null,
        variety: "Cambia según la edición",
        process: "Cambia según la edición",
        altitude: "Cambia según la edición",
        link: "https://square.link/u/xxxxx",
      },
      {
        id: "oriori-wheel",
        image: "/images/atmosphere-2.jpg",
        title: "Rueda de Sabor",
        summary: "Un sitio para registrar y describir sabores",
        origin: "—",
        producer: null,
        variety: "—",
        process: "—",
        altitude: "—",
        link: "https://square.link/u/xxxxx",
      },
    ],
  },
};